/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/chair.glb 
Author: rfinterior (https://sketchfab.com/rocio133)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cover-chair-86c6d5e7bb954a949b9977decbd3009b
Title: Cover Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/models/chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-28.097, -24.826, -0.081]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.ig_100_100_100SG} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.phong1SG} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.phong1SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/chair.glb')
